In [3]:
import pandas as pd
s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
s=pd.Series([100,200,300],
            index=['A','B','C'])
print(s)

A    100
B    200
C    300
dtype: int64

In [6]:
data={
    'maths':90,
    'physics':80,
    'chemistry':88
}
s=pd.Series(data)
print(s)

maths        90
physics      80
chemistry    88
dtype: int64

In [9]:
s=pd.Series([10,20,30,40])
print(s[0])

10

In [10]:
s=pd.Series([100,200,300],
            index=['A','B','C'])
print(s['B'])

200

In [12]:
print(s[['A','C']])

A    100
C    300
dtype: int64

In [13]:
print(s.size)

3

In [14]:
print(s.shape)

(3,)

In [15]:
print(s.dtype)

int64

In [16]:
s=pd.Series([10,20,30,40])
print(s+10)

0    20
1    30
2    40
3    50
dtype: int64

In [17]:
print(s*2)

0    20
1    40
2    60
3    80
dtype: int64

In [21]:
print("Sum =",s.sum())
print("Mean =",s.mean())
print("Maximum =",s.max())
print("Minimum =",s.min())

Sum = 100
Mean = 25.0
Maximum = 40
Minimum = 10

In [5]:
import pandas as pd
data={
    'RollNo':[101,102,103],
'Name':['Arun','Priya','Rahul'],
'Marks':[85,90,78]
}
df=pd.DataFrame(data)
print(df)

   RollNo   Name  Marks
0     101   Arun     85
1     102  Priya     90
2     103  Rahul     78

In [24]:
df=pd.DataFrame(data,
                index=['A','B','C'])
print(df)

   RollNo   Name  Marks
A     101   Arun     85
B     102  Priya     90
C     103  Rahul     78

In [25]:
print(df.columns)

Index(['RollNo', 'Name', 'Marks'], dtype='object')

In [26]:
print(df.index)

Index(['A', 'B', 'C'], dtype='object')

In [27]:
print(df.dtypes)

RollNo     int64
Name      object
Marks      int64
dtype: object

In [29]:
print(df[['Name','Marks']])

    Name  Marks
A   Arun     85
B  Priya     90
C  Rahul     78

In [34]:
print(df['Name'])

A     Arun
B    Priya
C    Rahul
Name: Name, dtype: object

In [40]:
print(df.loc['A'])

RollNo     101
Name      Arun
Marks       85
Name: A, dtype: object

In [42]:
print(df.loc[['A','C']])

   RollNo   Name  Marks
A     101   Arun     85
C     103  Rahul     78

In [43]:
print(df.iloc[1])

RollNo      102
Name      Priya
Marks        90
Name: B, dtype: object

In [44]:
print(df.iloc[[0,2]])

   RollNo   Name  Marks
A     101   Arun     85
C     103  Rahul     78

In [45]:
print(df.iloc[0:2,1:3])

    Name  Marks
A   Arun     85
B  Priya     90

In [47]:
df['Grade']=['A','A+','B']
print(df)

   RollNo   Name  Marks Grade
A     101   Arun     85     A
B     102  Priya     90    A+
C     103  Rahul     78     B

In [11]:
df['Marks']=df['Marks']+5
print(df)

   RollNo   Name  Marks
0     101   Arun    100
1     102  Priya    105
2     103  Rahul     93

In [6]:

df.drop('Grade',
        axis=1,
        inplace=true)

KeyError: "['Grade'] not found in axis"

In [9]:
print(df)

   RollNo   Name  Marks
0     101   Arun     95
1     102  Priya    100
2     103  Rahul     88

In [10]:
print(df['Marks'].sum())

283

In [13]:
print(df['Marks'].mean())
print(df['Marks'].max())

99.33333333333333
105

In [14]:
print(df['Marks'].min())

93

In [15]:
df.sort_values('Marks')

   RollNo   Name  Marks
2     103  Rahul     93
0     101   Arun    100
1     102  Priya    105

In [16]:
df.sort_values('Marks',
               ascending=False)

   RollNo   Name  Marks
1     102  Priya    105
0     101   Arun    100
2     103  Rahul     93

In [2]:
import pandas as pd
data={
    'RollNo':[101,102,103],
'Name':['Arun','Priya','Rahul'],
'Marks':[85,90,78]
}
df=pd.DataFrame(data)
df.sort_values('Marks',
               ascending=True)

   RollNo   Name  Marks
2     103  Rahul     78
0     101   Arun     85
1     102  Priya     90

In [4]:
print(df[df['Marks']<90])

   RollNo   Name  Marks
0     101   Arun     85
2     103  Rahul     78

In [5]:
df.head()

   RollNo   Name  Marks
0     101   Arun     85
1     102  Priya     90
2     103  Rahul     78

In [7]:
data={
    'RollNo':[101,102,103,104,105,106,107,108,109,110],
'Name':['Arun','Priya','Rahul','Sandy','Anbu','Deena','Raj','Pranav','Mani','Ram'],
'Marks':[85,90,78,45,66,77,88,99,56,77]
}
df=pd.DataFrame(data)
df.tail()

   RollNo    Name  Marks
5     106   Deena     77
6     107     Raj     88
7     108  Pranav     99
8     109    Mani     56
9     110     Ram     77

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RollNo  10 non-null     int64
 1   Name    10 non-null     object
 2   Marks   10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

In [9]:
df.describe()

          RollNo      Marks
count   10.00000  10.000000
mean   105.50000  76.100000
std      3.02765  16.387326
min    101.00000  45.000000
25%    103.25000  68.750000
50%    105.50000  77.500000
75%    107.75000  87.250000
max    110.00000  99.000000

In [12]:
data={
    'RollNo':[101,102,103,104,105,106,107,108,109,110],
'Name':['Arun','Priya','Rahul','Sandy','Anbu','Deena','Raj','Pranav','Mani','Ram'],
'Dept':['CS','DS','AI','Hrm','Ca','Bcom','ML','BCA','MCA','BBA'],
'Cgpa':[7,8,9,9,6,7,8,8,9,8]
}
df=pd.DataFrame(data)
print(df)

   RollNo    Name  Dept  Cgpa
0     101    Arun    CS     7
1     102   Priya    DS     8
2     103   Rahul    AI     9
3     104   Sandy   Hrm     9
4     105    Anbu    Ca     6
5     106   Deena  Bcom     7
6     107     Raj    ML     8
7     108  Pranav   BCA     8
8     109    Mani   MCA     9
9     110     Ram   BBA     8

In [15]:
data={
    'RollNo':[101,102,103,104,105,106,107,108,109,110],
'Name':['Arun','Priya','Rahul','Sandy','Anbu','Deena','Raj','Pranav','Mani','Ram'],
'Marks':[85,90,78,45,66,77,88,99,56,77]
}
df=pd.DataFrame(data)
print(df['Marks'].sum())
print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].min())

761
76.1
99
45

In [17]:
data={
'Name':['Arun','Priya','Rahul','Sandy','Anbu'],
'Salary':[85000,50000,38000,48000,55000]
}
df=pd.DataFrame(data)
print(df[df['Salary']>40000])

    Name  Salary
0   Arun   85000
1  Priya   50000
3  Sandy   48000
4   Anbu   55000

In [18]:
df.sort_values('Salary',
               ascending=True)

    Name  Salary
2  Rahul   38000
3  Sandy   48000
1  Priya   50000
4   Anbu   55000
0   Arun   85000

In [6]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Ibscai29.DGVC-MCA\Documents\students.csv.csv")
print(df)

   RollNo   Name Department  Marks
0     101   Arun        CSE     85
1     102  Priya         AI     92
2     103  Rahul         IT     78
3     104  Divya        CSE     88

In [7]:
print(df.size)

16

In [8]:
print(df.shape)

(4, 4)

In [9]:
print(df.describe)

<bound method NDFrame.describe of    RollNo   Name Department  Marks
0     101   Arun        CSE     85
1     102  Priya         AI     92
2     103  Rahul         IT     78
3     104  Divya        CSE     88>

In [10]:
df.head(2)

   RollNo   Name Department  Marks
0     101   Arun        CSE     85
1     102  Priya         AI     92

In [11]:
df.tail(2)

   RollNo   Name Department  Marks
2     103  Rahul         IT     78
3     104  Divya        CSE     88

In [16]:
df.dtypes

RollNo         int64
Name          object
Department    object
Marks          int64
dtype: object

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   RollNo      4 non-null      int64
 1   Name        4 non-null      object
 2   Department  4 non-null      object
 3   Marks       4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [18]:
print(df.loc(1))

<pandas.core.indexing._LocIndexer object at 0x000001B44C8A7D40>

In [20]:
print(df.iloc[2])

RollNo          103
Name          Rahul
Department       IT
Marks            78
Name: 2, dtype: object

In [21]:
print(df[df["Marks"]>80])

   RollNo   Name Department  Marks
0     101   Arun        CSE     85
1     102  Priya         AI     92
3     104  Divya        CSE     88

In [22]:
df["Grade"]=["A","A","B","A"]
print(df)

   RollNo   Name Department  Marks Grade
0     101   Arun        CSE     85     A
1     102  Priya         AI     92     A
2     103  Rahul         IT     78     B
3     104  Divya        CSE     88     A

In [24]:
df["Marks"]=df["Marks"]+5
print(df)

   RollNo   Name Department  Marks Grade
0     101   Arun        CSE     90     A
1     102  Priya         AI     97     A
2     103  Rahul         IT     83     B
3     104  Divya        CSE     93     A